[cosmic-ray]
module-path = "lists/views.py"
python-version = ""
timeout = 10.0
excluded-modules = []
test-command = ".env/bin/python manage.py test lists"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []

[cosmic-ray.interceptors]
enabled = [ "spor", "pragma_no_mutate", "operators-filter",]

[cosmic-ray.operators-filter]
